name: "NPM Validation Action"
description: "Runs npm validation"
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      with:
        version: 7
        run_install: false

    - name: Install packages
      shell: bash
      run: |
        pnpm install
        cd test
        pnpm install

    - name: Check format
      shell: bash
      run: pnpm lint
    - name: Build
      shell: bash
      run: pnpm build
    - name: Run tests
      shell: bash
      run: pnpm test
