# Based on https://github.com/taiki-e/parse-changelog/blob/777a82184bcbe0ed975e63a491f5fbf80b29cb1b/.github/workflows/ci.yml

name: NPM CI

permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows other workflows to call this one
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Install packages
        run: |
          pnpm install
          cd test
          pnpm install

      - name: Check format
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
