# Based on https://github.com/taiki-e/parse-changelog/blob/777a82184bcbe0ed975e63a491f5fbf80b29cb1b/.github/workflows/release.yml

name: NPM Main CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]

defaults:
  run:
    shell: bash

jobs:
  call_npm_validation:
    uses: ./.github/workflows/npm_validation.yml
    secrets: inherit
